### ISSUE TITLE
How get data from firebase them?

### ISSUE THREAD

**Issue by minasvisual** [davideast/angular-modular-firebase#1]
I'm trying getting data for firebase on TaskComponent but the promise do not show any data function:
<pre>
 asyncApp.database().then(app => {
      console.log('post-loading database & auth app', app);
     ???????
    });
</pre>
Can you help me?

**Comment by davideast** [comment]
@minasvisual This is an experimental repo. Also this just resolves the Firebase app instance. You are now able to use it to get data.

**Comment by minasvisual** [comment]
Hi, i use the base for study angular 2 too. I already do. Thanks a lot.
